### ISSUE TITLE
Sondar patrocínios de Hoteis

### ISSUE THREAD

**Issue by gilsondev** [grupydf/python-cerrado#3]
Verificar a possibilidade de patrocínio de hoteis com capacidade para ceder a Python Cerrado, com ou sem buffet. Além disso aproveitar para trazer orçamentos quando não tem a possibilidade de apoio.

**Comment by alexandrebarbaruiva** [comment]
# Estimativa de preços

Os hotéis sondados foram o Carlton Hotel, San Marco Hotel, Phenícia Bittar Hotel, Meliã Hotel e o Brasil 21, que é um hotel e centro de convenções .
Valores referentes à tabela de preços de 2017, provável que em Janeiro de 2018 haja reajuste de 10 a 20% do previsto.

## Detalhamento

Pedido de locação consistiu de 3 salas, sendo 1 auditório para 150 pessoas e 2 salas para 50 pessoas. Os preços variaram entre **R$2800 e  R$8200 por dia** para somente locação (sem wifi nem coffee break).

Todos os locais confirmaram a possibilidade de descontos, principalmente se houvesse número alto de hóspedes, porém nenhum local forneceu estimativa de desconto ou qualquer informação similar. É possível pedir orçamento para mais detalhes.

Coffee break, caso seja solicitado, deve ser do próprio hotel, e custa em média R$35 p/ pessoa (no nosso caso de 4 C.B.'s no total, o gasto seria de MUITA grana, nem vou colocar aqui pra gente continuar o dia feliz).

Wifi está disponível no formato de links ou pontos de acesso, sendo viável apenas links para nosso caso, com o menor pacote (5 Mbs) custando em torno de R$1500, não entrei muito em detalhes nesta questão, posso aprofundar mais depois caso seja necessário.

A quantidade de tomadas das salas se provou muito boa, mas ainda seria necessário levar réguas e coisas do gênero.

Algumas salas não possuíam parede que fosse possível projetar.

## Custo básico diário individual

### [Carlton Hotel](http://www.carltonhotelbrasilia.com.br/)

1 Auditório -  R$1500 + 10%
2 salas - R$1500 + 10%
Total: R$3000 + 10%

### [San Marco Hotel](https://sanmarco.com.br/site/)

1 Auditório -  R$2000 + 10%
2 salas - R$2600 + 10%
Total: R$4600 + 10%

### [Phenícia Bittar Hotel](https://hoteisbittar.com.br/phenicia/) 

1 Auditório -  R$1300 + 10%
2 salas - R$1500 + 10%
Total: R$2800 + 10%

### [Meliã Hotel](https://www1.melia.com/nPromociones/producto/onlyinmelia/jsp/C_Home.jsp)

Valores similares ao Brasil 21

### Brasil 21

- 1 Auditório -  R$5810 + 10%
- 2 salas - R$4780 + 10%
