### ISSUE TITLE
Iniciar conversas com a UnB para possível local

### ISSUE THREAD

**Issue by gilsondev** [grupydf/python-cerrado#5]
Efetuar as conversas com a UnB para ceder local que encaixe no perfil do evento que é:

 - 1 auditório para uso geral, como aberturas e fechamentos do evento e também palestras
 - 1 sala para palestras
 - 1 sala para openspaces e uso da Pyladies

Os departamentos a serem contactados serão:
 - FT: @Dayof 
 - FACE: @alexandrebarbaruiva

**Comment by taniaa** [comment]
@alexandrebarbaruiva a UNB já retornou do recesso pra continuar a conversa?

**Comment by alexandrebarbaruiva** [comment]
Está tendo aulas de verão, irei na FACE segunda
