### ISSUE TITLE
Iniciar conversas com a ESAF para possível local

### ISSUE THREAD

**Issue by gilsondev** [grupydf/python-cerrado#6]
Entrar em contato com as pessoas relacionadas a ESAF, baseado nos telefones e e-mails recebidos pela @taniaa que foram usados na Python Brasil de Brasília. A idéia é verificar se podem ajudar a negociarmos a possibilidade de cederem gratuitamente o espaço.

**Comment by taniaa** [comment]
@gilsondev Ok, pro IESB a Patrícia voltou de férias e pode marcar visita. Eu, a @Dayof e o @alexandrebarbaruiva podemos ir contigo...
Na ESAF conseguiu contactar?
E no CEUB?
