### ISSUE TITLE
Criar mídias sociais para o evento

### ISSUE THREAD

**Issue by gilsondev** [grupydf/python-cerrado#7]
- [ ] Página no Facebook

Aguardar issue #2 para criar a página.
Ao criar a página fazer primeiro post : "Save the date : 18, 19 de Agosto".

- [ ] Twitter

Aguardar issue #2 para criar a página.
Ao criar canal da Python Cerrado fazer primeiro Tweet : "Save the date : 18, 19 de Agosto".

**Comment by gilsondev** [comment]
Um outro canal interessante é o telegram:

https://ifttt.com/applets/352668p-post-your-tweets-on-your-telegram-channel

**Comment by taniaa** [comment]
Segue lista final das redes sociais criadas pela @Dayof e GitHub que criei:

Página no FB: https://www.facebook.com/pythoncerrado
E-mail: pythoncerrado@gmail.com
Twitter : @pythoncerrado | pythoncerrado@gmail.com
GitHub: https://github.com/pythoncerrado
